### PR TITLE
Add NTLM authentication support

### PR DESCRIPTION
**Pull request by czeumer**
### Description

Implemented the suggested changes and tested it in our environment.

### References

https://github.com/hashicorp/terraform-provider-ad/issues/34

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### CODE REVIEW

**Review by koikonom — CHANGES_REQUESTED** [review]
Hey @czeumer !  Thanks for taking the time to submit this PR. 

Code-wise I only have a minor comment to make that's really trivial to fix.
There seems to be a weird problem with the provider though. Specifically when I try to run the acceptance tests it seems that authentication fails randomly:

```
❯ TESTARGS='-count 1 -run TestAccADGroupMembership_basic' make testacc  | tee /tmp/lol.out
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -count 1 -run TestAccADGroupMembership_basic -timeout 120m
[...output...]
=== RUN   TestAccADGroupMembership_basic
    resource_ad_group_membership_test.go:14: terraform failed: exit status 1

        stderr:

        Error: powershell command failed with exit code 1
        stdout:
        stderr:
        error: http response error: 401 - invalid content type



        Error: powershell command failed with exit code 1
        stdout:
        stderr:
        error: http response error: 401 - invalid content type



        Error: powershell command failed with exit code 1
        stdout:
        stderr:
        error: http response error: 401 - invalid content type



--- FAIL: TestAccADGroupMembership_basic (7.41s)

[...output...]
❯ TESTARGS='-count 1 -run TestAccADGroupMembership_basic' make testacc  | tee /tmp/lol.out
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -count 1 -run TestAccADGroupMembership_basic -timeout 120m
[...output...]
=== RUN   TestAccADGroupMembership_basic
--- PASS: TestAccADGroupMembership_basic (28.28s)
PASS
ok  	github.com/hashicorp/terraform-provider-ad/ad	28.687s
?   	github.com/hashicorp/terraform-provider-ad/ad/internal/adschema	[no test files]
testing: warning: no tests to run
PASS
ok  	github.com/hashicorp/terraform-provider-ad/ad/internal/gposec	0.198s [no tests to run]
[...output...]
```

I am running the tests against a Win2k12R2 server and my test server has this setup:
```
winrm quickconfig -q
winrm set winrm/config/winrs '@{MaxMemoryPerShellMB="300"}'
winrm set winrm/config '@{MaxTimeoutms="1800000"}'
winrm set winrm/config/service '@{AllowUnencrypted="true"}'
winrm set winrm/config/service/auth '@{Basic="true"}'
```

**Comment by czeumer** [comment]
> There seems to be a weird problem with the provider though. Specifically when I try to run the acceptance tests it seems that authentication fails randomly:

Hi @koikonom,

it seems, that an NTLM authenticated session does not allow to be used in parallel.  
We implemented a simple connection pooling, that ensures a WinRM connection is used exclusively during a run.

**Comment by koikonom** [comment]
Hi @czeumer thanks for adding the connection pooling too, the tests no longer fail. 

Unfortunately I cannot merge the PR as is until you rebase on top of the `main` branch, due to conflicts. Let me know once you do that and I'll merge this!

**Comment by czeumer** [comment]
hi @koikonom 
> 
> Unfortunately I cannot merge the PR as is until you rebase on top of the `main` branch, due to conflicts. Let me know once you do that and I'll merge this!

The PR has been rebased.

**Pull request merged**
